# Generated by Django 5.0.1 on 2024-02-16 18:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Apartamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero_apartamento', models.CharField(choices=[('Apto 01', 'Apto 01'), ('Apto 02', 'Apto 02'), ('Apto 03', 'Apto 03'), ('Apto 04', 'Apto 04'), ('Apto 05', 'Apto 05'), ('Apto 06', 'Apto 06'), ('Apto 07', 'Apto 07'), ('Apto 08', 'Apto 08'), ('Apto 09', 'Apto 09'), ('Apto 10', 'Apto 10')], max_length=50)),
            ],
        ),
        migrations.CreateModel(
            name='VagaDupla',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaga_dupla', models.CharField(choices=[('Vaga 01 e 02', 'Vaga 01 e 02'), ('Vaga 03 e 04', 'Vaga 03 e 04'), ('Vaga 05 e 06', 'Vaga 05 e 06'), ('Vaga 07 e 08', 'Vaga 07 e 08'), ('Vaga 09 e 10', 'Vaga 09 e 10'), ('Vaga 11 e 12', 'Vaga 11 e 12'), ('Vaga 13 e 14', 'Vaga 13 e 14'), ('Vaga 15 e 16', 'Vaga 15 e 16'), ('Vaga 17 e 18', 'Vaga 17 e 18'), ('Vaga 19 e 20', 'Vaga 19 e 20')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='VagaSimples',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaga_simples', models.CharField(choices=[('Vaga 01', 'Vaga 01'), ('Vaga 02', 'Vaga 02'), ('Vaga 03', 'Vaga 03'), ('Vaga 04', 'Vaga 04'), ('Vaga 05', 'Vaga 05'), ('Vaga 06', 'Vaga 06'), ('Vaga 07', 'Vaga 07'), ('Vaga 08', 'Vaga 08'), ('Vaga 09', 'Vaga 09'), ('Vaga 10', 'Vaga 10')], max_length=50, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Sorteio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartamento', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nova_colina.apartamento')),
                ('vaga_dupla', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nova_colina.vagadupla')),
                ('vaga_simples', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='nova_colina.vagasimples')),
            ],
        ),
    ]
