# Generated by Django 5.0.1 on 2024-01-23 14:29

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ListaDePresenca',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('apartamento', models.CharField(max_length=100)),
                ('bloco', models.CharField(max_length=100)),
                ('presenca', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='VagaEscolher',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vaga', models.CharField(max_length=100)),
                ('apartamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='apartamentos', to='sorteio_novo.listadepresenca')),
                ('bloco', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='blocos', to='sorteio_novo.listadepresenca')),
            ],
        ),
    ]
