# Generated by Django 5.0.1 on 2024-01-23 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteio_novo', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listadepresenca',
            name='bloco',
            field=models.CharField(default='-', max_length=100),
        ),
        migrations.AlterField(
            model_name='listadepresenca',
            name='presenca',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
