# Generated by Django 5.0.1 on 2024-01-23 15:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteio_novo', '0002_alter_listadepresenca_bloco_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listadepresenca',
            name='presenca',
            field=models.BooleanField(default=False, null=True),
        ),
    ]
