# Generated by Django 5.0.1 on 2024-01-24 18:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteio_novo', '0003_alter_listadepresenca_presenca'),
    ]

    operations = [
        migrations.AddField(
            model_name='listadepresenca',
            name='vaga',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
