# Generated by Django 5.0.1 on 2024-01-24 19:36

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteio_novo', '0004_listadepresenca_vaga'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='listadepresenca',
            name='vaga',
        ),
        migrations.AlterField(
            model_name='vagaescolher',
            name='apartamento',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='apartamentos', to='sorteio_novo.listadepresenca'),
        ),
        migrations.AlterField(
            model_name='vagaescolher',
            name='bloco',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='blocos', to='sorteio_novo.listadepresenca'),
        ),
    ]
