# Generated by Django 5.0.1 on 2024-01-25 13:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteio_novo', '0005_remove_listadepresenca_vaga_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vagaescolher',
            name='apartamento',
        ),
        migrations.RemoveField(
            model_name='vagaescolher',
            name='bloco',
        ),
        migrations.AddField(
            model_name='vagaescolher',
            name='presenca',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='vagas', to='sorteio_novo.listadepresenca'),
        ),
    ]
