# Generated by Django 5.0.1 on 2024-01-25 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sorteio_novo', '0006_remove_vagaescolher_apartamento_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='vagaescolher',
            old_name='presenca',
            new_name='lista_de_presenca',
        ),
    ]
