# Generated by Django 5.0.1 on 2024-01-25 14:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteio_novo', '0009_listadepresenca_vaga_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listadepresenca',
            name='vaga',
            field=models.CharField(blank=True, choices=[('vaga1', 'Vaga 1'), ('vaga2', 'Vaga 2')], max_length=100, null=True),
        ),
    ]
