# Generated by Django 5.0.1 on 2024-01-25 17:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteio_novo', '0010_alter_listadepresenca_vaga'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listadepresenca',
            name='apartamento',
            field=models.CharField(choices=[('apto 01', 'apartamento 01'), ('apto 02', 'apartamento 02'), ('apto 03', 'apartamento 03'), ('apto 04', 'apartamento 04'), ('apto 05', 'apartamento 05')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listadepresenca',
            name='vaga',
            field=models.CharField(blank=True, choices=[('vaga 01', 'Vaga 01'), ('vaga 02', 'Vaga 02'), ('vaga 03', 'Vaga 03'), ('vaga 04', 'Vaga 04'), ('vaga 05', 'Vaga 05')], max_length=100, null=True),
        ),
    ]
