# Generated by Django 5.0.1 on 2024-01-25 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sorteio_novo', '0011_alter_listadepresenca_apartamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='listadepresenca',
            name='apartamento',
            field=models.CharField(choices=[('Apto 01', 'apartamento 01'), ('Apto 02', 'apartamento 02'), ('Apto 03', 'apartamento 03'), ('Apto 04', 'apartamento 04'), ('Apto 05', 'apartamento 05')], max_length=100),
        ),
        migrations.AlterField(
            model_name='listadepresenca',
            name='vaga',
            field=models.CharField(blank=True, choices=[('Vaga 01', 'Vaga 01'), ('Vaga 02', 'Vaga 02'), ('Vaga 03', 'Vaga 03'), ('Vaga 04', 'Vaga 04'), ('Vaga 05', 'Vaga 05')], max_length=100, null=True),
        ),
    ]
