# Generated by Django 5.0.1 on 2024-02-16 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chacara_bom_sucesso', '0002_alter_apartamento_numero_apartamento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vaga',
            name='vaga',
            field=models.CharField(choices=[('Vaga 01', 'Vaga 01'), ('Vaga 02', 'Vaga 02'), ('Vaga 03', 'Vaga 03'), ('Vaga 04', 'Vaga 04'), ('Vaga 05', 'Vaga 05'), ('Vaga 06', 'Vaga 06'), ('Vaga 07', 'Vaga 07'), ('Vaga 08', 'Vaga 08'), ('Vaga 09', 'Vaga 09'), ('Vaga 10', 'Vaga 10'), ('Vaga 11', 'Vaga 11'), ('Vaga 12', 'Vaga 12'), ('Vaga 13', 'Vaga 13'), ('Vaga 14', 'Vaga 14'), ('Vaga 15', 'Vaga 15'), ('Vaga 16', 'Vaga 16'), ('Vaga 17', 'Vaga 17'), ('Vaga 18', 'Vaga 18'), ('Vaga 19', 'Vaga 19'), ('Vaga 20', 'Vaga 20'), ('Vaga 21', 'Vaga 21'), ('Vaga 22', 'Vaga 22'), ('Vaga 23', 'Vaga 23'), ('Vaga 24', 'Vaga 24'), ('Vaga 25', 'Vaga 25'), ('Vaga 26', 'Vaga 26'), ('Vaga 27', 'Vaga 27'), ('Vaga 28', 'Vaga 28'), ('Vaga 29', 'Vaga 29'), ('Vaga 30', 'Vaga 30'), ('Vaga 31', 'Vaga 31'), ('Vaga 32', 'Vaga 32'), ('Vaga 33', 'Vaga 33'), ('Vaga 34', 'Vaga 34'), ('Vaga 35', 'Vaga 35'), ('Vaga 36', 'Vaga 36'), ('Vaga 37', 'Vaga 37'), ('Vaga 38', 'Vaga 38'), ('Vaga 39', 'Vaga 39'), ('Vaga 40', 'Vaga 40'), ('Vaga 41', 'Vaga 41'), ('Vaga 42', 'Vaga 42'), ('Vaga 43', 'Vaga 43'), ('Vaga 44', 'Vaga 44'), ('Vaga 45', 'Vaga 45'), ('Vaga 46', 'Vaga 46'), ('Vaga 47', 'Vaga 47'), ('Vaga 48', 'Vaga 48'), ('Vaga 49', 'Vaga 49'), ('Vaga 50', 'Vaga 50')], max_length=50, unique=True),
        ),
    ]
